[build]
  publish = "build" # CRA outputs to "build"
  command = "npm run build"

[[redirects]]
  from = "/merci*"
  to = "/merci.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
